In [14]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import streamlit as st
import psutil
import os
import datetime


from mainnet_launch.constants import AutopoolConstants, PRODUCTION_LOG_FILE_NAME, STARTUP_LOG_FILE, AUTO_ETH
from mainnet_launch.data_fetching.get_state_by_block import build_blocks_to_use
from mainnet_launch.pages.autopool_diagnostics.fetch_destination_summary_stats import fetch_destination_summary_stats
from mainnet_launch.destinations import get_destination_details

from mainnet_launch.database.schema.full import (
    AutopoolStates,
    Blocks,
    DestinationStates,
    AutopoolDestinationStates,
    Destinations,
)
from mainnet_launch.database.schema.postgres_operations import natural_left_right_using_where, get_full_table_as_df


autopool = AUTO_ETH

destination_state_df = natural_left_right_using_where(
    DestinationStates,
    AutopoolDestinationStates,
    using=[DestinationStates.chain_id, DestinationStates.block, DestinationStates.destination_vault_address],
    where_clause=AutopoolDestinationStates.autopool_vault_address == autopool.autopool_eth_addr,
)

destinations_df = get_full_table_as_df(Destinations)
destination_state_df = pd.merge(
    destination_state_df, get_full_table_as_df(Destinations), on=["destination_vault_address", "chain_id"]
)
blocks_df = get_full_table_as_df(Blocks, where_clause=Blocks.chain_id == autopool.chain.chain_id)
destination_state_df = pd.merge(
    destination_state_df,
    get_full_table_as_df(Blocks, where_clause=Blocks.chain_id == autopool.chain.chain_id),
    on=["block", "chain_id"],
)

destination_state_df

2025-05-01 12:53:18,312 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-01 12:53:18,313 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-01 12:53:18,314 INFO sqlalchemy.engine.Engine [cached since 423.4s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x12f1cac80>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-01 12:53:18,314 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM destination_states
            JOIN autopool_destination_states
            USING (chain_id, block, destination_vault_address)
            WHERE autopool_destination_states.autopool_vault_address = '0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56'

2025-05-01 12:53:18,314 INFO sqlalchemy.engine.Engine [cached since 347.5s ago] {}
2025-05-01 12:53:19,230 INFO sqlalchemy.engine.Engine ROLLBACK
2025-05-01 12:53:19,324 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-01 12:53:19,324 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-01 12:53:19,325 INFO sqlalchemy.engine.Engine [cached since 424.4s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x12f1cab30>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-01 12:53:19,325 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM destinations


2025-05-01 12:53:19,326 INFO sqlalchemy.engine.Engine [cached since 299.1s ago] {}
2025-05-01 12:53:19,530 INFO sqlalchemy.engine.Engine ROLLBACK
2025-05-01 12:53:19,630 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-01 12:53:19,631 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-01 12:53:19,631 INFO sqlalchemy.engine.Engine [cached since 424.7s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x12ed5c430>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-01 12:53:19,632 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM destinations


2025-05-01 12:53:19,632 INFO sqlalchemy.engine.Engine [cached since 299.4s ago] {}
2025-05-01 12:53:19,824 INFO sqlalchemy.engine.Engine ROLLBACK
2025-05-01 12:53:19,925 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-01 12:53:19,926 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-01 12:53:19,927 INFO sqlalchemy.engine.Engine [cached since 425s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x12f1cb1f0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-01 12:53:19,927 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM blocks
            WHERE blocks.chain_id = 1

2025-05-01 12:53:19,928 INFO sqlalchemy.engine.Engine [generated in 0.00050s] {}
2025-05-01 12:53:20,188 INFO sqlalchemy.engine.Engine ROLLBACK
2025-05-01 12:53:20,286 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-01 12:53:20,287 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-01 12:53:20,288 INFO sqlalchemy.engine.Engine [cached since 425.3s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x12ee2a9e0>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-01 12:53:20,289 INFO sqlalchemy.engine.Engine
            SELECT *
            FROM blocks
            WHERE blocks.chain_id = 1

2025-05-01 12:53:20,289 INFO sqlalchemy.engine.Engine [cached since 0.3621s ago] {}
2025-05-01 12:53:20,484 INFO sqlalchemy.engine.Engine ROLLBACK

,chain_id,block,destination_vault_address,incentive_apr,fee_apr,base_apr,points_apr,fee_plus_base_apr,total_apr_in,total_apr_out,...,block_deployed,name,symbol,pool_type,pool,underlying,underlying_symbol,underlying_name,denominated_in,datetime
0,1,20759464,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0.041235,0.003997,0.005817,0.0,None,0.046281,0.046281,...,20756405,Tokemak-Wrapped Ether-Balancer rETH Stable Pool,toke-WETH-B-rETH-STABLE,balMetaStable,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,B-rETH-STABLE,Balancer rETH Stable Pool,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2024-09-15 23:59:59+00:00
1,1,20766617,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0.040938,0.003618,0.005802,0.0,None,0.045987,0.045987,...,20756405,Tokemak-Wrapped Ether-Balancer rETH Stable Pool,toke-WETH-B-rETH-STABLE,balMetaStable,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,B-rETH-STABLE,Balancer rETH Stable Pool,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2024-09-16 23:59:59+00:00
2,1,20773761,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0.040507,0.003295,0.005848,0.0,None,0.045061,0.045061,...,20756405,Tokemak-Wrapped Ether-Balancer rETH Stable Pool,toke-WETH-B-rETH-STABLE,balMetaStable,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,B-rETH-STABLE,Balancer rETH Stable Pool,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2024-09-17 23:59:59+00:00
3,1,20780916,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0.040196,0.003022,0.005817,0.0,None,0.044440,0.044440,...,20756405,Tokemak-Wrapped Ether-Balancer rETH Stable Pool,toke-WETH-B-rETH-STABLE,balMetaStable,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,B-rETH-STABLE,Balancer rETH Stable Pool,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2024-09-18 23:59:59+00:00
4,1,20788084,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0.040448,0.002794,0.005885,0.0,None,0.044524,0.044524,...,20756405,Tokemak-Wrapped Ether-Balancer rETH Stable Pool,toke-WETH-B-rETH-STABLE,balMetaStable,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,B-rETH-STABLE,Balancer rETH Stable Pool,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2024-09-19 23:59:59+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6598,1,22385293,0x5c6aeb9ef0d5BbA4E6691f381003503FD0D45126,0.043122,0.025627,0.022730,0.0,None,0.087167,0.087863,...,20918143,Tokemak-Wrapped Ether-weETH/WETH-ng,toke-WETH-weeth-ng,curveNG,0xDB74dfDD3BB46bE8Ce6C33dC9D82777BCFc3dEd5,0xDB74dfDD3BB46bE8Ce6C33dC9D82777BCFc3dEd5,weeth-ng,weETH/WETH-ng,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2025-04-30 23:59:59+00:00
6599,1,22378150,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,0.068286,0.000000,0.020292,0.0,None,0.081749,0.081937,...,22376699,Tokemak-Wrapped Ether-Curve.fi Factory Pool: OETH,toke-WETH-OETHCRV-f,curveV1,0x94B17476A93b3262d87B9a326965D1E91f9c13E7,0x94B17476A93b3262d87B9a326965D1E91f9c13E7,OETHCRV-f,Curve.fi Factory Pool: OETH,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2025-04-29 23:59:59+00:00
6600,1,22385293,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,0.069646,0.000000,0.020150,0.0,None,0.082832,0.082996,...,22376699,Tokemak-Wrapped Ether-Curve.fi Factory Pool: OETH,toke-WETH-OETHCRV-f,curveV1,0x94B17476A93b3262d87B9a326965D1E91f9c13E7,0x94B17476A93b3262d87B9a326965D1E91f9c13E7,OETHCRV-f,Curve.fi Factory Pool: OETH,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2025-04-30 23:59:59+00:00
6601,1,22378150,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,NaN,0.000000,0.000000,0.0,None,NaN,0.000000,...,20722908,autoETH,autoETH,idle,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,autoETH,autoETH,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2025-04-29 23:59:59+00:00
6602,1,22385293,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,NaN,0.000000,0.000000,0.0,None,NaN,0.000000,...,20722908,autoETH,autoETH,idle,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,autoETH,autoETH,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,2025-04-30 23:59:59+00:00

In [30]:
destination_state_df.columns

Index(['chain_id', 'block', 'destination_vault_address', 'incentive_apr',
       'fee_apr', 'base_apr', 'points_apr', 'fee_plus_base_apr',
       'total_apr_in', 'total_apr_out', 'underlying_token_total_supply',
       'safe_total_supply', 'price_per_share', 'price_return',
       'underlying_safe_price', 'underlying_spot_price', 'underlying_backing',
       'safe_backing_discount', 'spot_backing_discount', 'safe_spot_spread',
       'autopool_vault_address', 'amount', 'total_safe_value',
       'total_spot_value', 'total_backing_value', 'percent_ownership',
       'exchange_name', 'block_deployed', 'name', 'symbol', 'pool_type',
       'pool', 'underlying', 'underlying_symbol', 'underlying_name',
       'denominated_in', 'datetime'],
      dtype='object')

In [ ]:
destination_state_df[""]  # in autopool states

In [ ]:
# must be sepearte because of we removed and added some destinations
composite_return_out_df = destination_state_df.pivot(
    index="datetime", values="total_apr_out", columns="destination_vault_address"
)
price_return_df = destination_state_df.pivot(
    index="datetime", values="price_return", columns="destination_vault_address"
)
owned_shares_df = destination_state_df.pivot(index="datetime", values="amount", columns="destination_vault_address")
price_per_share_df = destination_state_df.pivot(
    index="datetime", values="price_per_share", columns="destination_vault_address"
)

allocation_df = price_per_share_df * owned_shares_df
total_nav_series = allocation_df.sum(axis=1)
portion_df = allocation_df / total_nav_series

destination_state_df["unweighted_apr"] = destination_state_df[["fee_apr", "base_apr", "incentive_apr"]].sum(axis=1)

unweighted_apr_by_destination = destination_state_df.pivot(
    index="datetime", values="price_per_share", columns="unweighted_apr"
)

expected_return = (portion_df.fillna(0) * unweighted_apr_by_destination.fillna(0)).sum(axis=1)

In [19]:
px.bar(destination_state_df.pivot(index="datetime", values="total_safe_value", columns="destination_vault_address"))

In [31]:
destination_state_df.pivot(index="datetime", values="total_safe_value", columns="destination_vault_address")

destination_vault_address,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x1Ea622fa030e4a78F4CC2f305dd3c08DA3F08573,0x25cb41919d6B88e0D48108A4F5fe8FBb3744aFE1,0x2B08137BeABd2454AD3631DEB754F97C5c93eB78,0x356c79Ab2B2cEFAB685004CE827146058A6c3e77,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,0x3F55eedDe51504E6Ed0ec30E8289b4Da11EdB7F9,0x40219bBda953ca811d2D0168Dc806a96b84791d9,0x5A4B544B9734930DDC587c9a2f093dC5058A4f4D,0x5c6aeb9ef0d5BbA4E6691f381003503FD0D45126,...,0xE382BBd32C4E202185762eA433278f4ED9E6151E,0xFDa49984eb4eA4075b8b451032849347C633E94b,0xbA1462f43c6f60ebD1C62735c94E428aD073E01A,0xc4Eb861e7b66f593482a3D7E8adc314f6eEDA30B,0xd96E943098B2AE81155e98D7DC8BeaB34C539f01,0xdfE3fA7027E84f59b266459C567278C79fe86f0C,0xe3AE2Ab9AE8ADe1B4940dd893C9339401bEe61A1,0xe4433D00Cf48BFE0C672d9949F2cd2c008bffC04,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0xfB6f99FdF12E37Bfe3c4Cf81067faB10c465fb24
datetime,,,,,,,,,,,,,,,,,,,,,
2024-09-15 23:59:59+00:00,0.239949,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,NaN,0.0,NaN,0.0,0.0
2024-09-16 23:59:59+00:00,944.081116,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,NaN,0.0,NaN,0.0,0.0
2024-09-17 23:59:59+00:00,1554.391314,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.989238,NaN,NaN,NaN,0.000000,NaN,0.0,NaN,0.0,0.0
2024-09-18 23:59:59+00:00,2572.961608,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,414.397542,NaN,NaN,NaN,146.016553,NaN,0.0,NaN,0.0,0.0
2024-09-19 23:59:59+00:00,2471.666099,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,750.049556,NaN,NaN,NaN,280.653069,NaN,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-27 23:59:59+00:00,110.472695,1715.652090,0.0,0.0,0.0,NaN,666.017979,1.489080e+14,0.0,1840.796211,...,0.000000,0.0,3380.385836,1.435927e+14,0.000000,567.303294,0.0,5803.122075,0.0,0.0
2025-04-28 23:59:59+00:00,273.545207,1715.913951,0.0,0.0,0.0,NaN,910.397645,1.489009e+14,0.0,1840.626047,...,0.000000,0.0,3382.150864,1.435926e+14,0.000000,567.416532,0.0,5806.489261,0.0,0.0
2025-04-29 19:08:11+00:00,179.973418,1716.033056,0.0,0.0,0.0,NaN,972.141156,2.340471e+14,0.0,1840.999000,...,0.000000,0.0,3382.123472,1.435926e+14,0.000000,567.440854,0.0,5806.598644,0.0,0.0
2025-04-29 23:59:59+00:00,179.975418,1716.037217,NaN,NaN,NaN,0.000000,971.893253,2.339334e+14,NaN,1841.003111,...,NaN,NaN,3382.073062,1.435926e+14,NaN,567.440854,NaN,5806.520454,NaN,NaN
2025-04-30 23:59:59+00:00,188.715846,1715.735655,NaN,NaN,NaN,89.161574,1036.187098,2.320325e+14,NaN,1840.465289,...,NaN,NaN,3382.062823,1.435925e+14,NaN,567.322516,NaN,5806.288375,NaN,NaN

destination_vault_address,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x1Ea622fa030e4a78F4CC2f305dd3c08DA3F08573,0x25cb41919d6B88e0D48108A4F5fe8FBb3744aFE1,0x2B08137BeABd2454AD3631DEB754F97C5c93eB78,0x356c79Ab2B2cEFAB685004CE827146058A6c3e77,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,0x3F55eedDe51504E6Ed0ec30E8289b4Da11EdB7F9,0x40219bBda953ca811d2D0168Dc806a96b84791d9,0x5A4B544B9734930DDC587c9a2f093dC5058A4f4D,0x5c6aeb9ef0d5BbA4E6691f381003503FD0D45126,...,0xE382BBd32C4E202185762eA433278f4ED9E6151E,0xFDa49984eb4eA4075b8b451032849347C633E94b,0xbA1462f43c6f60ebD1C62735c94E428aD073E01A,0xc4Eb861e7b66f593482a3D7E8adc314f6eEDA30B,0xd96E943098B2AE81155e98D7DC8BeaB34C539f01,0xdfE3fA7027E84f59b266459C567278C79fe86f0C,0xe3AE2Ab9AE8ADe1B4940dd893C9339401bEe61A1,0xe4433D00Cf48BFE0C672d9949F2cd2c008bffC04,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0xfB6f99FdF12E37Bfe3c4Cf81067faB10c465fb24
datetime,,,,,,,,,,,,,,,,,,,,,
2024-09-15 23:59:59+00:00,0.239949,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,NaN,0.0,NaN,0.0,0.0
2024-09-16 23:59:59+00:00,944.081116,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,NaN,0.0,NaN,0.0,0.0
2024-09-17 23:59:59+00:00,1554.391314,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.989238,NaN,NaN,NaN,0.000000,NaN,0.0,NaN,0.0,0.0
2024-09-18 23:59:59+00:00,2572.961608,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,414.397542,NaN,NaN,NaN,146.016553,NaN,0.0,NaN,0.0,0.0
2024-09-19 23:59:59+00:00,2471.666099,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,750.049556,NaN,NaN,NaN,280.653069,NaN,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-04-27 23:59:59+00:00,110.472695,1715.652090,0.0,0.0,0.0,NaN,666.017979,1.489080e+14,0.0,1840.796211,...,0.000000,0.0,3380.385836,1.435927e+14,0.000000,567.303294,0.0,5803.122075,0.0,0.0
2025-04-28 23:59:59+00:00,273.545207,1715.913951,0.0,0.0,0.0,NaN,910.397645,1.489009e+14,0.0,1840.626047,...,0.000000,0.0,3382.150864,1.435926e+14,0.000000,567.416532,0.0,5806.489261,0.0,0.0
2025-04-29 19:08:11+00:00,179.973418,1716.033056,0.0,0.0,0.0,NaN,972.141156,2.340471e+14,0.0,1840.999000,...,0.000000,0.0,3382.123472,1.435926e+14,0.000000,567.440854,0.0,5806.598644,0.0,0.0
2025-04-29 23:59:59+00:00,179.975418,1716.037217,NaN,NaN,NaN,0.000000,971.893253,2.339334e+14,NaN,1841.003111,...,NaN,NaN,3382.073062,1.435926e+14,NaN,567.440854,NaN,5806.520454,NaN,NaN
2025-04-30 23:59:59+00:00,188.715846,1715.735655,NaN,NaN,NaN,89.161574,1036.187098,2.320325e+14,NaN,1840.465289,...,NaN,NaN,3382.062823,1.435925e+14,NaN,567.322516,NaN,5806.288375,NaN,NaN

,destination_vault_address,chain_id,exchange_name,block_deployed,name,symbol,pool_type,pool,underlying,underlying_symbol,underlying_name,denominated_in
0,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,1,balancer,20756405,Tokemak-Wrapped Ether-Balancer rETH Stable Pool,toke-WETH-B-rETH-STABLE,balMetaStable,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,0x1E19CF2D73a72Ef1332C882F20534B6519Be0276,B-rETH-STABLE,Balancer rETH Stable Pool,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
1,0x865e59D439BF7310c9BC6117E6020B8C87De4065,1,balancer,20756406,Tokemak-Wrapped Ether-Balancer osETH/wETH Stab...,toke-WETH-osETH/wETH-BPT,balCompStable,0xDACf5Fa19b1f720111609043ac67A9818262850c,0xDACf5Fa19b1f720111609043ac67A9818262850c,osETH/wETH-BPT,Balancer osETH/wETH StablePool,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
2,0x25cb41919d6B88e0D48108A4F5fe8FBb3744aFE1,1,balancer,20756407,Tokemak-Wrapped Ether-Balancer wstETH-WETH Sta...,toke-WETH-wstETH-WETH-BPT,balCompStable,0x93d199263632a4EF4Bb438F1feB99e57b4b5f0BD,0x93d199263632a4EF4Bb438F1feB99e57b4b5f0BD,wstETH-WETH-BPT,Balancer wstETH-WETH Stable Pool,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
3,0x6DcB6797b1C0442587c2ad79745ef7BB487Fc2E2,1,balancer,20756408,Tokemak-Wrapped Ether-Gyroscope ECLP wstETH/wETH,toke-WETH-ECLP-wstETH-wETH,balGyro,0xf01b0684C98CD7aDA480BFDF6e43876422fa1Fc1,0xf01b0684C98CD7aDA480BFDF6e43876422fa1Fc1,ECLP-wstETH-wETH,Gyroscope ECLP wstETH/wETH,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
4,0xe3AE2Ab9AE8ADe1B4940dd893C9339401bEe61A1,1,balancer,20756409,Tokemak-Wrapped Ether-Gyroscope ECLP wstETH/cbETH,toke-WETH-ECLP-wstETH-cbETH,balGyro,0xF7A826D47c8E02835D94fb0Aa40F0cC9505cb134,0xF7A826D47c8E02835D94fb0Aa40F0cC9505cb134,ECLP-wstETH-cbETH,Gyroscope ECLP wstETH/cbETH,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
...,...,...,...,...,...,...,...,...,...,...,...,...
95,0x58C2233399B85b53C5506f78eAaae9b0DBA1eD3E,8453,aerodrome,22326389,Tokemak-Wrapped Ether-Volatile AMM - WETH/wstETH,toke-WETH-vAMM-WETH/wstETH,vAMM,0xA6385c73961dd9C58db2EF0c4EB98cE4B60651e8,0xA6385c73961dd9C58db2EF0c4EB98cE4B60651e8,vAMM-WETH/wstETH,Volatile AMM - WETH/wstETH,0x4200000000000000000000000000000000000006
96,0xA94031Ed4b316B043464FDd5482877F42A39845a,8453,aerodrome,22326389,Tokemak-Wrapped Ether-Volatile AMM - WETH/wrsETH,toke-WETH-vAMM-WETH/wrsETH,vAMM,0xA24382874A6FD59de45BbccFa160488647514c28,0xA24382874A6FD59de45BbccFa160488647514c28,vAMM-WETH/wrsETH,Volatile AMM - WETH/wrsETH,0x4200000000000000000000000000000000000006
97,0xd18db4dD6aF6A7536aD7F863C136463681e0CdAD,8453,aerodrome,22326389,Tokemak-Wrapped Ether-Volatile AMM - cbETH/WETH,toke-WETH-vAMM-cbETH/WETH,vAMM,0x44Ecc644449fC3a9858d2007CaA8CFAa4C561f91,0x44Ecc644449fC3a9858d2007CaA8CFAa4C561f91,vAMM-cbETH/WETH,Volatile AMM - cbETH/WETH,0x4200000000000000000000000000000000000006
98,0xBd137c56f3116E5c36753037a784FF844F84F59c,8453,balancer,22661893,Tokemak-Wrapped Ether-Gyroscope ECLP cbETH/wstETH,toke-WETH-ECLP-cbETH-wstETH,balGyro,0x54D86E177cdC664B5F9B17eB5fd6A76Fa529e466,0x54D86E177cdC664B5F9B17eB5fd6A76Fa529e466,ECLP-cbETH-wstETH,Gyroscope ECLP cbETH/wstETH,0x4200000000000000000000000000000000000006
99,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,8453,tokemak,21241103,baseETH,baseETH,idle,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,0xAADf01DD90aE0A6Bb9Eb908294658037096E0404,baseETH,baseETH,0x4200000000000000000000000000000000000006