In [ ]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import streamlit as st
import psutil

from mainnet_launch.constants import AutopoolConstants

from mainnet_launch.database.schema.full import (
    AutopoolStates,
    Blocks,
    DestinationStates,
    Destinations,
    AutopoolDestinationStates,
    DestinationTokenValues,
    TokenValues,
    Tokens,
)
from mainnet_launch.database.schema.postgres_operations import (
    merge_tables_as_df,
    TableSelector,
)
from mainnet_launch.data_fetching.get_state_by_block import build_blocks_to_use


def fetch_nav_per_share(autopool: AutopoolConstants) -> pd.DataFrame:
    nav_per_share_df = merge_tables_as_df(
        [
            TableSelector(
                table=AutopoolStates,
                select_fields=AutopoolStates.nav_per_share,
                join_on=None,
                row_filter=(AutopoolStates.autopool_vault_address == autopool.autopool_eth_addr),
            ),
            TableSelector(
                table=Blocks,
                select_fields=Blocks.datetime,
                join_on=(AutopoolStates.chain_id == Blocks.chain_id) & (AutopoolStates.block == Blocks.block),
            ),
        ],
        where_clause=Blocks.block.in_(build_blocks_to_use(autopool.chain)),
        order_by=Blocks.datetime,
    )
    nav_per_share_df = nav_per_share_df.set_index("datetime")
    nav_per_share_df.columns = [autopool.name]

    nav_per_share_df["30_day_difference"] = nav_per_share_df[autopool.name].diff(periods=30)
    nav_per_share_df["30_day_annualized_return"] = (
        (nav_per_share_df["30_day_difference"] / nav_per_share_df[autopool.name].shift(30)) * (365 / 30) * 100
    )
    nav_per_share_df["7_day_difference"] = nav_per_share_df[autopool.name].diff(periods=7)
    nav_per_share_df["7_day_annualized_return"] = (
        (nav_per_share_df["7_day_difference"] / nav_per_share_df[autopool.name].shift(7)) * (365 / 7) * 100
    )
    nav_per_share_df["daily_return"] = nav_per_share_df[autopool.name].pct_change()
    nav_per_share_df["7_day_MA_return"] = nav_per_share_df["daily_return"].rolling(window=7).mean()
    nav_per_share_df["7_day_MA_annualized_return"] = nav_per_share_df["7_day_MA_return"] * 365 * 100
    nav_per_share_df["30_day_MA_return"] = nav_per_share_df["daily_return"].rolling(window=30).mean()
    nav_per_share_df["30_day_MA_annualized_return"] = nav_per_share_df["30_day_MA_return"] * 365 * 100
    return nav_per_share_df


def fetch_key_metrics_data(autopool: AutopoolConstants):
    nav_per_share_df = fetch_nav_per_share(autopool)

    destination_state_df = merge_tables_as_df(
        selectors=[
            TableSelector(
                DestinationStates,
                select_fields=[
                    DestinationStates.incentive_apr,
                    DestinationStates.fee_apr,
                    DestinationStates.base_apr,
                    DestinationStates.lp_token_safe_price
                ],
            ),
            TableSelector(
                AutopoolDestinationStates,
                [
                    AutopoolDestinationStates.owned_shares,
                ],
                (DestinationStates.destination_vault_address == AutopoolDestinationStates.destination_vault_address)
                & (DestinationStates.chain_id == AutopoolDestinationStates.chain_id)
                & (DestinationStates.block == AutopoolDestinationStates.block),
            ),
            TableSelector(
                Destinations,
                [Destinations.pool_type, Destinations.underlying_symbol],
                (DestinationStates.destination_vault_address == Destinations.destination_vault_address)
                & (DestinationStates.chain_id == Destinations.chain_id),
            ),
            TableSelector(
                Blocks,
                Blocks.datetime,
                (DestinationStates.block == Blocks.block) & (DestinationStates.chain_id == Blocks.chain_id),
            ),
        ],
        where_clause=(AutopoolDestinationStates.autopool_vault_address == autopool.autopool_eth_addr)
        & (Blocks.block.in_(build_blocks_to_use(autopool.chain))),
        order_by=Blocks.datetime,
    )

    destination_state_df["unweighted_apr"] = destination_state_df[["fee_apr", "base_apr", "incentive_apr"]].sum(axis=1)

    owned_shares_df = (
        destination_state_df.groupby(["datetime", "underlying_symbol"])[["owned_shares"]]
        .sum()
        .reset_index()
        .pivot(index="datetime", values="owned_shares", columns="underlying_symbol")
    )

    # I expect max and min to be the same for each destiantion here, if they exist at all
    highest_value_by_destination_symbol = (
        destination_state_df.groupby(["datetime", "underlying_symbol"])[
            ["price_per_share", "unweighted_apr", "price_return"]
        ]
        .max()
        .reset_index()
    )
    price_per_share_df = highest_value_by_destination_symbol.pivot(
        index="datetime", values="price_per_share", columns="underlying_symbol"
    )

    price_return_df = highest_value_by_destination_symbol.pivot(
        index="datetime", values="price_return", columns="underlying_symbol"
    )

    allocation_df = (price_per_share_df * owned_shares_df).fillna(0)
    total_nav_series = allocation_df.sum(axis=1)

    portion_df = allocation_df.div(total_nav_series, axis=0)

    uwcr_df = highest_value_by_destination_symbol.pivot(
        index="datetime", values="unweighted_apr", columns="underlying_symbol"
    )
    expected_return_series = 100 * (portion_df.fillna(0) * uwcr_df.fillna(0)).sum(axis=1)

    weighted_price_return_series = -100 * (portion_df.fillna(0) * price_return_df.fillna(0)).sum(axis=1)

    highest_block_and_datetime = destination_state_df[["block", "datetime"]].max()

    return (
        nav_per_share_df,
        total_nav_series,
        expected_return_series,
        allocation_df,
        weighted_price_return_series,
        highest_block_and_datetime,
        price_return_df,
        portion_df,
    )


from mainnet_launch.constants import AUTO_ETH, AUTO_USD
import plotly.io as pio

pio.templates.default = None

# (
#     nav_per_share_df,
#     total_nav_series,
#     expected_return_series,
#     allocation_df,
#     weighted_price_return_series,
#     highest_block_and_datetime,
#     price_return_df,
#     portion_df,
# ) = fetch_key_metrics_data(AUTO_USD)

# allocation_df

2025-05-08 11:54:13.086 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [2]:
# destination_state_df = merge_tables_as_df(
#     selectors=[
#         TableSelector(
#             DestinationStates,
#             select_fields=[
#                 DestinationStates.block,
#                 DestinationStates.price_per_share,
#                 DestinationStates.price_return,
#                 DestinationStates.underlying_token_total_supply,
#             ],
#         ),
#         TableSelector(
#             DestinationTokenValues,
#             select_fields=[
#                 DestinationTokenValues.spot_price,
#                 DestinationTokenValues.quantity,
#             ],
#             join_on=(
#                 (DestinationStates.destination_vault_address == DestinationTokenValues.destination_vault_address)
#                 & (DestinationStates.chain_id == DestinationTokenValues.chain_id)
#                 & (DestinationStates.block == DestinationTokenValues.block)
#             ),
#         ),
#         TableSelector(
#             Destinations,
#             select_fields=[
#                 Destinations.underlying_symbol,
#                 Destinations.pool_type,
#             ],
#             join_on=(
#                 (Destinations.destination_vault_address == DestinationStates.destination_vault_address)
#                 & (Destinations.chain_id == DestinationStates.chain_id)
#             ),
#         ),
#         TableSelector(
#             AutopoolDestinationStates,
#             select_fields=[AutopoolDestinationStates.owned_shares],
#             join_on=(
#                 (DestinationStates.destination_vault_address == AutopoolDestinationStates.destination_vault_address)
#                 & (DestinationStates.chain_id == AutopoolDestinationStates.chain_id)
#                 & (DestinationStates.block == AutopoolDestinationStates.block)
#             ),
#         ),
#         TableSelector(
#             TokenValues,
#             select_fields=[TokenValues.safe_price, TokenValues.backing, TokenValues.denominated_in],
#             join_on=(
#                 (DestinationTokenValues.token_address == TokenValues.token_address)
#                 & (DestinationTokenValues.chain_id == TokenValues.chain_id)
#                 & (DestinationTokenValues.block == TokenValues.block)
#             ),
#             row_filter=(TokenValues.denominated_in == AUTO_USD.base_asset),
#         ),
#         TableSelector(
#             Tokens,
#             select_fields=[Tokens.symbol,],
#             join_on=(
#                 (Tokens.token_address == TokenValues.token_address)
#                 & (Tokens.chain_id == TokenValues.chain_id)
#             ),
#             row_filter=(TokenValues.denominated_in == AUTO_USD.base_asset),
#         ),
#         TableSelector(
#             Blocks,
#             select_fields=[Blocks.datetime],
#             join_on=((DestinationStates.chain_id == Blocks.chain_id) & (DestinationStates.block == Blocks.block)),
#         ),
#     ],
#     where_clause=(
#         (AutopoolDestinationStates.autopool_vault_address == AUTO_USD.autopool_eth_addr)
#         & (Blocks.block.in_(build_blocks_to_use(AUTO_USD.chain)))
#     ),
#     order_by=Blocks.datetime,
# )

# destination_state_df

In [3]:
destination_state_df = merge_tables_as_df(
    selectors=[
        TableSelector(
            DestinationStates,
            select_fields=[
                DestinationStates.price_return,
                DestinationStates.underlying_token_total_supply,
            ],
        ),
        TableSelector(
            Destinations,
            select_fields=[
                Destinations.underlying_symbol,
                Destinations.pool_type,
            ],
            join_on=(
                (Destinations.destination_vault_address == DestinationStates.destination_vault_address)
                & (Destinations.chain_id == DestinationStates.chain_id)
            ),
        ),
        TableSelector(
            AutopoolDestinationStates,
            select_fields=[AutopoolDestinationStates.owned_shares],
            join_on=(
                (DestinationStates.destination_vault_address == AutopoolDestinationStates.destination_vault_address)
                & (DestinationStates.chain_id == AutopoolDestinationStates.chain_id)
                & (DestinationStates.block == AutopoolDestinationStates.block)
            ),
        ),
        TableSelector(
            Blocks,
            select_fields=[Blocks.datetime],
            join_on=((DestinationStates.chain_id == Blocks.chain_id) & (DestinationStates.block == Blocks.block)),
        ),
    ],
    where_clause=(
        (AutopoolDestinationStates.autopool_vault_address == AUTO_ETH.autopool_eth_addr)
        & (Blocks.block.in_(build_blocks_to_use(AUTO_ETH.chain)))
    ),
    order_by=Blocks.datetime,
)

destination_state_df

2025-05-08 11:54:13.098 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:13.155
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /Users/pb/Library/Caches/pypoetry/virtualenvs/mainnet-launch-FtycU18g-py3.10/lib/python3.10/site-packages/ipykernel_launcher.py [ARGUMENTS]
2025-05-08 11:54:13.156 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:13.156 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:13.156 No runtime found, using MemoryCacheStorageManager
2025-05-08 11:54:13.662 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:13.665 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.

2025-05-08 11:54:14,924 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-05-08 11:54:14,926 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-08 11:54:15,195 INFO sqlalchemy.engine.Engine select current_schema()
2025-05-08 11:54:15,196 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-08 11:54:15,389 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-05-08 11:54:15,391 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-05-08 11:54:15,578 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-08 11:54:15,598 INFO sqlalchemy.engine.Engine SELECT max(blocks.block) AS block
FROM blocks
WHERE blocks.chain_id = %(chain_id_1)s AND blocks.block >= %(block_1)s AND blocks.block <= %(block_2)s GROUP BY date_trunc(%(date_trunc_1)s, blocks.datetime) ORDER BY date_trunc(%(date_trunc_2)s, blocks.datetime)
2025-05-08 11:54:15,598 INFO sqlalchemy.engine.Engine [generated in 0.00061s] {'chain_id_1': 1, 'block_1': 20752910, 'block_2': 100000000, 'date_trunc_1': 'day', 'date_trunc_2': 'day'}
2025-05-08 11:54:15,841 INFO sqlalchemy.engine.Engine COMMIT

2025-05-08 11:54:15.940 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:15.943 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

2025-05-08 11:54:15,948 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-08 11:54:15,948 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-08 11:54:15,949 INFO sqlalchemy.engine.Engine [generated in 0.00112s] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x12d7a6d70>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-08 11:54:15,950 INFO sqlalchemy.engine.Engine SELECT
    destination_states.price_return,
    destination_states.underlying_token_total_supply,
    destinations.underlying_symbol,
    destinations.pool_type,
    autopool_destination_states.owned_shares,
    blocks.datetime
FROM destination_states
JOIN destinations
  ON destinations.destination_vault_address = destination_states.destination_vault_address AND destinations.chain_id = destination_states.chain_id
JOIN autopool_destination_states
  ON destination_states.destination_vault_address = autopool_destination_states.destination_vault_address AND destination_states.chain_id = autopool_destination_states.chain_id AND destination_states.block = autopool_destination_states.block
JOIN blocks
  ON destination_states.chain_id = blocks.chain_id AND destination_states.block = blocks.block
WHERE
    (autopool_destination_states.autopool_vault_address = '0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56' AND blocks.block IN (20759464, 20766617, 20773761, 20780916, 20788084, 20795238, 20802389, 20809562, 20816725, 20823901, 20831060, 20838231, 20845405, 20852572, 20859740, 20866918, 20874085, 20881261, 20888424, 20895606, 20902784, 20909955, 20917130, 20924302, 20931482, 20938657, 20945811, 20952957, 20960089, 20967244, 20974401, 20981560, 20988724, 20995892, 21003063, 21010230, 21017401, 21024558, 21031733, 21038905, 21046076, 21053236, 21060412, 21067570, 21074738, 21081894, 21089068, 21096238, 21103392, 21110559, 21117728, 21124888, 21132050, 21139209, 21146367, 21153541, 21160714, 21167883, 21175045, 21182212, 21189371, 21196531, 21203703, 21210874, 21218049, 21225225, 21232385, 21239548, 21246710, 21253879, 21261045, 21268202, 21275369, 21282522, 21289632, 21296777, 21303933, 21311105, 21318259, 21325415, 21332578, 21339732, 21346894, 21354047, 21361217, 21368389, 21375545, 21382702, 21389868, 21397030, 21404196, 21411356, 21418529, 21425699, 21432852, 21440009, 21447175, 21454314, 21461471, 21468617, 21475764, 21482924, 21490077, 21497235, 21504401, 21511571, 21518734, 21525890, 21533058, 21540232, 21547396, 21554556, 21561709, 21568863, 21576035, 21583203, 21590362, 21597520, 21604680, 21611852, 21619004, 21626161, 21633325, 21640491, 21647653, 21654814, 21661974, 21669146, 21676305, 21683471, 21690636, 21697804, 21704966, 21712129, 21719303, 21726465, 21733626, 21740792, 21747949, 21755110, 21762264, 21769421, 21776574, 21783739, 21790905, 21798074, 21805232, 21812397, 21819559, 21826720, 21833845, 21840991, 21848119, 21855250, 21862393, 21869537, 21876698, 21883855, 21890993, 21898155, 21905310, 21912465, 21919621, 21926782, 21933948, 21941120, 21948291, 21955462, 21962635, 21969800, 21976966, 21984128, 21991286, 21998438, 22005590, 22012750, 22019907, 22027064, 22034224, 22041393, 22048553, 22055722, 22062883, 22070044, 22077198, 22084356, 22091518, 22098694, 22105862, 22113034, 22120200, 22127350, 22134526, 22141688, 22148848, 22156001, 22163172, 22170334, 22177499, 22184669, 22191826, 22198999, 22206150, 22213305, 22220455, 22227624, 22234793, 22241970, 22249146, 22256323, 22263499, 22270667, 22277825, 22284996, 22292157, 22299326, 22306493, 22313650, 22320818, 22327989, 22335153, 22342307, 22349480, 22356658, 22363838, 22370998, 22378150, 22385293, 22392426, 22399543, 22406692, 22413825, 22420967, 22428091))
ORDER BY
    blocks.datetime ASC

2025-05-08 11:54:15,950 INFO sqlalchemy.engine.Engine [generated in 0.00043s] {}
2025-05-08 11:54:17,166 INFO sqlalchemy.engine.Engine ROLLBACK

,price_return,underlying_token_total_supply,underlying_symbol,pool_type,owned_shares,datetime
0,NaN,NaN,pxETH/wETH,balCompStable,NaN,2024-09-15 23:59:59+00:00
1,NaN,NaN,weETH/rETH,balCompStable,NaN,2024-09-15 23:59:59+00:00
2,NaN,NaN,osETH-rETH,curveNG,NaN,2024-09-15 23:59:59+00:00
3,NaN,NaN,ethx-f,curveV1,NaN,2024-09-15 23:59:59+00:00
4,NaN,NaN,wETHrETH,curveNG,NaN,2024-09-15 23:59:59+00:00
...,...,...,...,...,...,...
7015,0.0,7869.081442,pxsteth,curveNG,5711.036028,2025-05-06 23:59:59+00:00
7016,0.0,5523.370331,pxethweth,curveNG,3379.646932,2025-05-06 23:59:59+00:00
7017,NaN,5940.046784,frxeth-ng-f,curveV1,0.000000,2025-05-06 23:59:59+00:00
7018,0.0,5833.743590,weeth-ng,curveNG,1760.056918,2025-05-06 23:59:59+00:00
7019,0.0,17103.326987,OETHCRV-f,curveV1,1182.015728,2025-05-06 23:59:59+00:00

In [4]:
destination_state_df["portion_ownership"] = (
    destination_state_df["owned_shares"] / destination_state_df["underlying_token_total_supply"]
)
destination_state_df

,price_return,underlying_token_total_supply,underlying_symbol,pool_type,owned_shares,datetime,portion_ownership
0,NaN,NaN,pxETH/wETH,balCompStable,NaN,2024-09-15 23:59:59+00:00,NaN
1,NaN,NaN,weETH/rETH,balCompStable,NaN,2024-09-15 23:59:59+00:00,NaN
2,NaN,NaN,osETH-rETH,curveNG,NaN,2024-09-15 23:59:59+00:00,NaN
3,NaN,NaN,ethx-f,curveV1,NaN,2024-09-15 23:59:59+00:00,NaN
4,NaN,NaN,wETHrETH,curveNG,NaN,2024-09-15 23:59:59+00:00,NaN
...,...,...,...,...,...,...,...
7015,0.0,7869.081442,pxsteth,curveNG,5711.036028,2025-05-06 23:59:59+00:00,0.725756
7016,0.0,5523.370331,pxethweth,curveNG,3379.646932,2025-05-06 23:59:59+00:00,0.611881
7017,NaN,5940.046784,frxeth-ng-f,curveV1,0.000000,2025-05-06 23:59:59+00:00,0.000000
7018,0.0,5833.743590,weeth-ng,curveNG,1760.056918,2025-05-06 23:59:59+00:00,0.301703
7019,0.0,17103.326987,OETHCRV-f,curveV1,1182.015728,2025-05-06 23:59:59+00:00,0.069110

In [5]:
total_supply_df = (
    destination_state_df.groupby(["datetime", "underlying_symbol"])["underlying_token_total_supply"]
    .sum()
    .reset_index()
    .pivot(index="datetime", values="underlying_token_total_supply", columns="underlying_symbol")
    .fillna(0)
)


owned_shares_df = (
    destination_state_df.groupby(["datetime", "underlying_symbol"])["owned_shares"]
    .sum()
    .reset_index()
    .pivot(index="datetime", values="owned_shares", columns="underlying_symbol")
    .fillna(0)
)

In [6]:
portion_ownership_df = owned_shares_df / total_supply_df

px.line(portion_ownership_df)

In [7]:
price_return_df = (
    destination_state_df.groupby(["datetime", "underlying_symbol"])["price_return"]
    .min()
    .reset_index()
    .pivot(index="datetime", values="price_return", columns="underlying_symbol")
    .fillna(0)
)

px.line(price_return_df)

In [8]:
px.line((-100 * price_return_df * portion_ownership_df).sum(axis=1))
# the portion is wrong, it should be out TVL / autopool tvl
# not out % ownerhsip of the pool

In [9]:
destination_state_df = merge_tables_as_df(
    selectors=[
        TableSelector(
            DestinationStates,
            select_fields=[
                DestinationStates.destination_vault_address,
                DestinationStates.block,
                DestinationStates.incentive_apr,
                DestinationStates.fee_apr,
                DestinationStates.base_apr,
                DestinationStates.price_per_share,
                DestinationStates.price_return,
                DestinationStates.lp_token_spot_price,
            ],
        ),
        TableSelector(
            AutopoolDestinationStates,
            [
                AutopoolDestinationStates.owned_shares,
            ],
            (DestinationStates.destination_vault_address == AutopoolDestinationStates.destination_vault_address)
            & (DestinationStates.chain_id == AutopoolDestinationStates.chain_id)
            & (DestinationStates.block == AutopoolDestinationStates.block),
        ),
        TableSelector(
            Destinations,
            [Destinations.pool_type],
            (DestinationStates.destination_vault_address == Destinations.destination_vault_address)
            & (DestinationStates.chain_id == Destinations.chain_id),
        ),
        TableSelector(
            AutopoolStates,
            [AutopoolStates.total_nav],
            (AutopoolStates.autopool_vault_address == AUTO_ETH.autopool_eth_addr)
            & (AutopoolStates.chain_id == DestinationStates.chain_id)
            & (AutopoolStates.block == DestinationStates.block),
        ),
        TableSelector(
            Blocks,
            Blocks.datetime,
            (DestinationStates.block == Blocks.block) & (DestinationStates.chain_id == Blocks.chain_id),
        ),
    ],
    where_clause=(AutopoolDestinationStates.autopool_vault_address == AUTO_ETH.autopool_eth_addr)
    & (Blocks.block.in_(build_blocks_to_use(AUTO_ETH.chain))),
    order_by=Blocks.datetime,
)

owned_shares_df = destination_state_df.pivot(
    index="datetime", values="owned_shares", columns="destination_vault_address"
)

price_per_share_df = destination_state_df.pivot(
    index="datetime", values="price_per_share", columns="destination_vault_address"
)

allocation_df = (price_per_share_df * owned_shares_df).fillna(0)
total_nav_series = allocation_df.sum(axis=1)

portion_df = allocation_df.div(total_nav_series, axis=1)

destination_state_df["unweighted_apr"] = destination_state_df[["fee_apr", "base_apr", "incentive_apr"]].sum(axis=1)

uwcr_df = destination_state_df.pivot(index="datetime", values="unweighted_apr", columns="destination_vault_address")
expected_return_series = 100 * (portion_df.fillna(0) * uwcr_df.fillna(0)).sum(axis=1)

price_return_df = destination_state_df.pivot(
    index="datetime", values="price_return", columns="destination_vault_address"
)

# pretty sure the issue here is that it is not properly grouping values by price return
# price return is still not correct
weighted_price_return_series = -100 * (portion_df.fillna(0) * price_return_df.fillna(0)).sum(axis=1)

2025-05-08 11:54:17.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:17.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:17.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:17.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:17.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

2025-05-08 11:54:17,602 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-08 11:54:17,603 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-08 11:54:17,603 INFO sqlalchemy.engine.Engine [cached since 1.655s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x138c8ea70>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-08 11:54:17,603 INFO sqlalchemy.engine.Engine SELECT
    destination_states.destination_vault_address,
    destination_states.block,
    destination_states.incentive_apr,
    destination_states.fee_apr,
    destination_states.base_apr,
    destination_states.price_per_share,
    destination_states.price_return,
    destination_states.lp_token_spot_price,
    autopool_destination_states.owned_shares,
    destinations.pool_type,
    autopool_states.total_nav,
    blocks.datetime
FROM destination_states
JOIN autopool_destination_states
  ON destination_states.destination_vault_address = autopool_destination_states.destination_vault_address AND destination_states.chain_id = autopool_destination_states.chain_id AND destination_states.block = autopool_destination_states.block
JOIN destinations
  ON destination_states.destination_vault_address = destinations.destination_vault_address AND destination_states.chain_id = destinations.chain_id
JOIN autopool_states
  ON autopool_states.autopool_vault_address = '0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56' AND autopool_states.chain_id = destination_states.chain_id AND autopool_states.block = destination_states.block
JOIN blocks
  ON destination_states.block = blocks.block AND destination_states.chain_id = blocks.chain_id
WHERE
    (autopool_destination_states.autopool_vault_address = '0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56' AND blocks.block IN (20759464, 20766617, 20773761, 20780916, 20788084, 20795238, 20802389, 20809562, 20816725, 20823901, 20831060, 20838231, 20845405, 20852572, 20859740, 20866918, 20874085, 20881261, 20888424, 20895606, 20902784, 20909955, 20917130, 20924302, 20931482, 20938657, 20945811, 20952957, 20960089, 20967244, 20974401, 20981560, 20988724, 20995892, 21003063, 21010230, 21017401, 21024558, 21031733, 21038905, 21046076, 21053236, 21060412, 21067570, 21074738, 21081894, 21089068, 21096238, 21103392, 21110559, 21117728, 21124888, 21132050, 21139209, 21146367, 21153541, 21160714, 21167883, 21175045, 21182212, 21189371, 21196531, 21203703, 21210874, 21218049, 21225225, 21232385, 21239548, 21246710, 21253879, 21261045, 21268202, 21275369, 21282522, 21289632, 21296777, 21303933, 21311105, 21318259, 21325415, 21332578, 21339732, 21346894, 21354047, 21361217, 21368389, 21375545, 21382702, 21389868, 21397030, 21404196, 21411356, 21418529, 21425699, 21432852, 21440009, 21447175, 21454314, 21461471, 21468617, 21475764, 21482924, 21490077, 21497235, 21504401, 21511571, 21518734, 21525890, 21533058, 21540232, 21547396, 21554556, 21561709, 21568863, 21576035, 21583203, 21590362, 21597520, 21604680, 21611852, 21619004, 21626161, 21633325, 21640491, 21647653, 21654814, 21661974, 21669146, 21676305, 21683471, 21690636, 21697804, 21704966, 21712129, 21719303, 21726465, 21733626, 21740792, 21747949, 21755110, 21762264, 21769421, 21776574, 21783739, 21790905, 21798074, 21805232, 21812397, 21819559, 21826720, 21833845, 21840991, 21848119, 21855250, 21862393, 21869537, 21876698, 21883855, 21890993, 21898155, 21905310, 21912465, 21919621, 21926782, 21933948, 21941120, 21948291, 21955462, 21962635, 21969800, 21976966, 21984128, 21991286, 21998438, 22005590, 22012750, 22019907, 22027064, 22034224, 22041393, 22048553, 22055722, 22062883, 22070044, 22077198, 22084356, 22091518, 22098694, 22105862, 22113034, 22120200, 22127350, 22134526, 22141688, 22148848, 22156001, 22163172, 22170334, 22177499, 22184669, 22191826, 22198999, 22206150, 22213305, 22220455, 22227624, 22234793, 22241970, 22249146, 22256323, 22263499, 22270667, 22277825, 22284996, 22292157, 22299326, 22306493, 22313650, 22320818, 22327989, 22335153, 22342307, 22349480, 22356658, 22363838, 22370998, 22378150, 22385293, 22392426, 22399543, 22406692, 22413825, 22420967, 22428091))
ORDER BY
    blocks.datetime ASC

2025-05-08 11:54:17,603 INFO sqlalchemy.engine.Engine [generated in 0.00033s] {}
2025-05-08 11:54:18,087 INFO sqlalchemy.engine.Engine ROLLBACK

In [10]:
owned_shares_df = destination_state_df.pivot(
    index="datetime", values="owned_shares", columns="destination_vault_address"
).fillna(0)
owned_shares_df

destination_vault_address,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x1Ea622fa030e4a78F4CC2f305dd3c08DA3F08573,0x25cb41919d6B88e0D48108A4F5fe8FBb3744aFE1,0x2B08137BeABd2454AD3631DEB754F97C5c93eB78,0x356c79Ab2B2cEFAB685004CE827146058A6c3e77,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,0x3F55eedDe51504E6Ed0ec30E8289b4Da11EdB7F9,0x40219bBda953ca811d2D0168Dc806a96b84791d9,0x5A4B544B9734930DDC587c9a2f093dC5058A4f4D,0x5c6aeb9ef0d5BbA4E6691f381003503FD0D45126,...,0xE382BBd32C4E202185762eA433278f4ED9E6151E,0xFDa49984eb4eA4075b8b451032849347C633E94b,0xbA1462f43c6f60ebD1C62735c94E428aD073E01A,0xc4Eb861e7b66f593482a3D7E8adc314f6eEDA30B,0xd96E943098B2AE81155e98D7DC8BeaB34C539f01,0xdfE3fA7027E84f59b266459C567278C79fe86f0C,0xe3AE2Ab9AE8ADe1B4940dd893C9339401bEe61A1,0xe4433D00Cf48BFE0C672d9949F2cd2c008bffC04,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0xfB6f99FdF12E37Bfe3c4Cf81067faB10c465fb24
datetime,,,,,,,,,,,,,,,,,,,,,
2024-09-15 23:59:59+00:00,0.239949,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0
2024-09-16 23:59:59+00:00,944.081116,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0
2024-09-17 23:59:59+00:00,1554.391314,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.000000,...,99.989600,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0
2024-09-18 23:59:59+00:00,2572.961608,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.000000,...,414.370225,0.0,0.000000,0.000000,144.704960,0.000000,0.0,0.000000,0.0,0.0
2024-09-19 23:59:59+00:00,2471.666099,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0.000000,...,749.985422,0.0,0.000000,0.000000,278.168795,0.000000,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-05-02 23:59:59+00:00,182.593540,1650.286018,0.0,0.0,0.0,286.856419,1045.33242,133.648066,0.0,1760.056918,...,0.000000,0.0,3379.646932,352.439573,0.000000,553.948632,0.0,5711.036028,0.0,0.0
2025-05-03 23:59:59+00:00,141.916823,1650.286018,0.0,0.0,0.0,389.696195,1045.33242,133.648066,0.0,1760.056918,...,0.000000,0.0,3379.646932,352.439573,0.000000,553.948632,0.0,5711.036028,0.0,0.0
2025-05-04 23:59:59+00:00,298.095343,1650.286018,0.0,0.0,0.0,644.500752,1045.33242,133.648066,0.0,1760.056918,...,0.000000,0.0,3379.646932,352.439573,0.000000,553.948632,0.0,5711.036028,0.0,0.0
2025-05-05 23:59:59+00:00,491.096947,1650.286018,0.0,0.0,0.0,926.867397,1045.33242,133.648066,0.0,1760.056918,...,0.000000,0.0,3379.646932,352.439573,0.000000,553.948632,0.0,5711.036028,0.0,0.0
2025-05-06 23:59:59+00:00,201.167074,1650.286018,0.0,0.0,0.0,1182.015728,1045.33242,133.648066,0.0,1760.056918,...,0.000000,0.0,3379.646932,352.439573,0.000000,553.948632,0.0,5711.036028,0.0,0.0

In [11]:
price_per_share_df = destination_state_df.pivot(
    index="datetime", values="price_per_share", columns="destination_vault_address"
)
price_per_share_df

destination_vault_address,0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56,0x1Ea622fa030e4a78F4CC2f305dd3c08DA3F08573,0x25cb41919d6B88e0D48108A4F5fe8FBb3744aFE1,0x2B08137BeABd2454AD3631DEB754F97C5c93eB78,0x356c79Ab2B2cEFAB685004CE827146058A6c3e77,0x3772973f8F399D74488D5cF3276C032E0afC8A6f,0x3F55eedDe51504E6Ed0ec30E8289b4Da11EdB7F9,0x40219bBda953ca811d2D0168Dc806a96b84791d9,0x5A4B544B9734930DDC587c9a2f093dC5058A4f4D,0x5c6aeb9ef0d5BbA4E6691f381003503FD0D45126,...,0xE382BBd32C4E202185762eA433278f4ED9E6151E,0xFDa49984eb4eA4075b8b451032849347C633E94b,0xbA1462f43c6f60ebD1C62735c94E428aD073E01A,0xc4Eb861e7b66f593482a3D7E8adc314f6eEDA30B,0xd96E943098B2AE81155e98D7DC8BeaB34C539f01,0xdfE3fA7027E84f59b266459C567278C79fe86f0C,0xe3AE2Ab9AE8ADe1B4940dd893C9339401bEe61A1,0xe4433D00Cf48BFE0C672d9949F2cd2c008bffC04,0xf3ae3c74EaD129e770A864CeE291A805b170bBe0,0xfB6f99FdF12E37Bfe3c4Cf81067faB10c465fb24
datetime,,,,,,,,,,,,,,,,,,,,,
2024-09-15 23:59:59+00:00,1.0,NaN,1.030580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.999302,NaN,NaN,NaN,1.008197,NaN,1.019615,NaN,1.036523,1.010355
2024-09-16 23:59:59+00:00,1.0,NaN,1.030646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.998932,NaN,NaN,NaN,1.007898,NaN,1.019481,NaN,1.036163,1.010071
2024-09-17 23:59:59+00:00,1.0,NaN,1.030473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.999996,NaN,NaN,NaN,1.008775,NaN,1.019102,NaN,1.036462,1.010095
2024-09-18 23:59:59+00:00,1.0,NaN,1.030944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000066,NaN,NaN,NaN,1.009064,NaN,1.020396,NaN,1.036491,1.010410
2024-09-19 23:59:59+00:00,1.0,NaN,1.030757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000086,NaN,NaN,NaN,1.008931,NaN,1.019541,NaN,1.036501,1.010333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-05-02 23:59:59+00:00,1.0,1.040117,NaN,1.023029,NaN,1.002048,1.043597,1.029347,NaN,1.046028,...,1.000714,NaN,1.000714,1.002363,1.016936,1.024718,NaN,1.016936,NaN,1.024718
2025-05-03 23:59:59+00:00,1.0,1.040191,NaN,1.023007,NaN,1.002078,1.043604,1.029323,NaN,1.046090,...,1.000736,NaN,1.000736,1.002414,1.016956,1.024737,NaN,1.016956,NaN,1.024737
2025-05-04 23:59:59+00:00,1.0,1.040292,NaN,1.023012,NaN,1.002077,1.043648,1.029336,NaN,1.046205,...,1.000792,NaN,1.000792,1.002460,1.017067,1.024848,NaN,1.017067,NaN,1.024848
2025-05-05 23:59:59+00:00,1.0,1.040266,NaN,1.022880,NaN,1.002144,1.043524,1.029236,NaN,1.046333,...,1.000786,NaN,1.000786,1.002449,1.017069,1.024801,NaN,1.017069,NaN,1.024801
2025-05-06 23:59:59+00:00,1.0,1.040406,NaN,1.022707,NaN,1.002182,1.043367,1.029074,NaN,1.046463,...,1.000909,NaN,1.000909,1.002576,1.017096,1.024794,NaN,1.017096,NaN,1.024794

In [12]:
destination_state_df = merge_tables_as_df(
    selectors=[
        # 1) Base table: DestinationStates
        TableSelector(
            DestinationStates,
            select_fields=[
                DestinationStates.destination_vault_address,
                DestinationStates.underlying_token_total_supply,
            ],
        ),
        # 2) AutopoolDestinationStates → join on vault+chain+block
        TableSelector(
            AutopoolDestinationStates,
            select_fields=[AutopoolDestinationStates.owned_shares],
            join_on=(
                (DestinationStates.destination_vault_address == AutopoolDestinationStates.destination_vault_address)
                & (DestinationStates.chain_id == AutopoolDestinationStates.chain_id)
                & (DestinationStates.block == AutopoolDestinationStates.block)
            ),
        ),
        # 4) Blocks → join on block+chain
        TableSelector(
            Blocks,
            select_fields=[Blocks.datetime],
            join_on=((DestinationStates.block == Blocks.block) & (DestinationStates.chain_id == Blocks.chain_id)),
        ),
    ],
    where_clause=(
        (AutopoolDestinationStates.autopool_vault_address == AUTO_ETH.autopool_eth_addr)
        & (Blocks.block.in_(build_blocks_to_use(AUTO_ETH.chain)))
    ),
    order_by=Blocks.datetime,
)

# care about (destination_vault_address,
destination_state_df["portion_ownership"] = (
    destination_state_df["owned_shares"] / destination_state_df["underlying_token_total_supply"]
)

2025-05-08 11:54:18.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:18.254 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:18.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:18.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:54:18.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

2025-05-08 11:54:18,259 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-08 11:54:18,259 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-08 11:54:18,259 INFO sqlalchemy.engine.Engine [cached since 2.312s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x138dd1c90>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-08 11:54:18,260 INFO sqlalchemy.engine.Engine SELECT
    destination_states.destination_vault_address,
    destination_states.underlying_token_total_supply,
    autopool_destination_states.owned_shares,
    blocks.datetime
FROM destination_states
JOIN autopool_destination_states
  ON destination_states.destination_vault_address = autopool_destination_states.destination_vault_address AND destination_states.chain_id = autopool_destination_states.chain_id AND destination_states.block = autopool_destination_states.block
JOIN blocks
  ON destination_states.block = blocks.block AND destination_states.chain_id = blocks.chain_id
WHERE
    (autopool_destination_states.autopool_vault_address = '0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56' AND blocks.block IN (20759464, 20766617, 20773761, 20780916, 20788084, 20795238, 20802389, 20809562, 20816725, 20823901, 20831060, 20838231, 20845405, 20852572, 20859740, 20866918, 20874085, 20881261, 20888424, 20895606, 20902784, 20909955, 20917130, 20924302, 20931482, 20938657, 20945811, 20952957, 20960089, 20967244, 20974401, 20981560, 20988724, 20995892, 21003063, 21010230, 21017401, 21024558, 21031733, 21038905, 21046076, 21053236, 21060412, 21067570, 21074738, 21081894, 21089068, 21096238, 21103392, 21110559, 21117728, 21124888, 21132050, 21139209, 21146367, 21153541, 21160714, 21167883, 21175045, 21182212, 21189371, 21196531, 21203703, 21210874, 21218049, 21225225, 21232385, 21239548, 21246710, 21253879, 21261045, 21268202, 21275369, 21282522, 21289632, 21296777, 21303933, 21311105, 21318259, 21325415, 21332578, 21339732, 21346894, 21354047, 21361217, 21368389, 21375545, 21382702, 21389868, 21397030, 21404196, 21411356, 21418529, 21425699, 21432852, 21440009, 21447175, 21454314, 21461471, 21468617, 21475764, 21482924, 21490077, 21497235, 21504401, 21511571, 21518734, 21525890, 21533058, 21540232, 21547396, 21554556, 21561709, 21568863, 21576035, 21583203, 21590362, 21597520, 21604680, 21611852, 21619004, 21626161, 21633325, 21640491, 21647653, 21654814, 21661974, 21669146, 21676305, 21683471, 21690636, 21697804, 21704966, 21712129, 21719303, 21726465, 21733626, 21740792, 21747949, 21755110, 21762264, 21769421, 21776574, 21783739, 21790905, 21798074, 21805232, 21812397, 21819559, 21826720, 21833845, 21840991, 21848119, 21855250, 21862393, 21869537, 21876698, 21883855, 21890993, 21898155, 21905310, 21912465, 21919621, 21926782, 21933948, 21941120, 21948291, 21955462, 21962635, 21969800, 21976966, 21984128, 21991286, 21998438, 22005590, 22012750, 22019907, 22027064, 22034224, 22041393, 22048553, 22055722, 22062883, 22070044, 22077198, 22084356, 22091518, 22098694, 22105862, 22113034, 22120200, 22127350, 22134526, 22141688, 22148848, 22156001, 22163172, 22170334, 22177499, 22184669, 22191826, 22198999, 22206150, 22213305, 22220455, 22227624, 22234793, 22241970, 22249146, 22256323, 22263499, 22270667, 22277825, 22284996, 22292157, 22299326, 22306493, 22313650, 22320818, 22327989, 22335153, 22342307, 22349480, 22356658, 22363838, 22370998, 22378150, 22385293, 22392426, 22399543, 22406692, 22413825, 22420967, 22428091))
ORDER BY
    blocks.datetime ASC

2025-05-08 11:54:18,261 INFO sqlalchemy.engine.Engine [generated in 0.00026s] {}
2025-05-08 11:54:18,519 INFO sqlalchemy.engine.Engine ROLLBACK

In [13]:
destination_state_df[["datetime", "destination_vault_address"]].value_counts().sort_values()

datetime                   destination_vault_address
2024-09-15 23:59:59+00:00  0x0A2b94F6871c1D7A32Fe58E1ab5e6deA2f114E56    1
                           0x3772973f8F399D74488D5cF3276C032E0afC8A6f    1
                           0x3F55eedDe51504E6Ed0ec30E8289b4Da11EdB7F9    1
                           0x40219bBda953ca811d2D0168Dc806a96b84791d9    1
                           0x5A4B544B9734930DDC587c9a2f093dC5058A4f4D    1
                                                                        ..
2025-05-06 23:59:59+00:00  0x3772973f8F399D74488D5cF3276C032E0afC8A6f    1
                           0x356c79Ab2B2cEFAB685004CE827146058A6c3e77    1
                           0x2B08137BeABd2454AD3631DEB754F97C5c93eB78    1
                           0xE382BBd32C4E202185762eA433278f4ED9E6151E    1
                           0xfB6f99FdF12E37Bfe3c4Cf81067faB10c465fb24    1
Name: count, Length: 7020, dtype: int64

In [20]:
token_value_df = merge_tables_as_df(
    selectors=[
        TableSelector(
            DestinationTokenValues,
            select_fields=[
                DestinationTokenValues.destination_vault_address,
                DestinationTokenValues.token_address,
                DestinationTokenValues.quantity,
            ],
        ),
        TableSelector(
            TokenValues,
            select_fields=[TokenValues.safe_price, TokenValues.backing],
            join_on=(
                (TokenValues.chain_id == DestinationTokenValues.chain_id)
                & (TokenValues.block == DestinationTokenValues.block)
                & (TokenValues.token_address == DestinationTokenValues.token_address)
                & (TokenValues.denominated_in == AUTO_ETH.base_asset)
            ),
        ),
        TableSelector(
            Tokens,
            select_fields=[Tokens.symbol],
            join_on=((Tokens.chain_id == TokenValues.chain_id) & (Tokens.token_address == TokenValues.token_address)),
        ),
        TableSelector(
            Blocks,
            select_fields=[Blocks.datetime],
            join_on=((TokenValues.block == Blocks.block) & (TokenValues.chain_id == Blocks.chain_id)),
        ),
    ],
    where_clause=((Blocks.block.in_(build_blocks_to_use(AUTO_ETH.chain)))),
    order_by=Blocks.datetime,
)

token_value_df

2025-05-08 11:56:06.895 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:56:06.895 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:56:06.896 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:56:06.897 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-05-08 11:56:06.897 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

2025-05-08 11:56:06,898 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-05-08 11:56:06,899 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-05-08 11:56:06,899 INFO sqlalchemy.engine.Engine [cached since 111s ago] {'table_name': <sqlalchemy.sql.elements.TextClause object at 0x138c8ff10>, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-05-08 11:56:06,899 INFO sqlalchemy.engine.Engine SELECT
    destination_token_values.destination_vault_address,
    destination_token_values.token_address,
    destination_token_values.quantity,
    token_values.safe_price,
    token_values.backing,
    tokens.symbol,
    blocks.datetime
FROM destination_token_values
JOIN token_values
  ON token_values.chain_id = destination_token_values.chain_id AND token_values.block = destination_token_values.block AND token_values.token_address = destination_token_values.token_address AND token_values.denominated_in = '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
JOIN tokens
  ON tokens.chain_id = token_values.chain_id AND tokens.token_address = token_values.token_address
JOIN blocks
  ON token_values.block = blocks.block AND token_values.chain_id = blocks.chain_id
WHERE
    (blocks.block IN (20759464, 20766617, 20773761, 20780916, 20788084, 20795238, 20802389, 20809562, 20816725, 20823901, 20831060, 20838231, 20845405, 20852572, 20859740, 20866918, 20874085, 20881261, 20888424, 20895606, 20902784, 20909955, 20917130, 20924302, 20931482, 20938657, 20945811, 20952957, 20960089, 20967244, 20974401, 20981560, 20988724, 20995892, 21003063, 21010230, 21017401, 21024558, 21031733, 21038905, 21046076, 21053236, 21060412, 21067570, 21074738, 21081894, 21089068, 21096238, 21103392, 21110559, 21117728, 21124888, 21132050, 21139209, 21146367, 21153541, 21160714, 21167883, 21175045, 21182212, 21189371, 21196531, 21203703, 21210874, 21218049, 21225225, 21232385, 21239548, 21246710, 21253879, 21261045, 21268202, 21275369, 21282522, 21289632, 21296777, 21303933, 21311105, 21318259, 21325415, 21332578, 21339732, 21346894, 21354047, 21361217, 21368389, 21375545, 21382702, 21389868, 21397030, 21404196, 21411356, 21418529, 21425699, 21432852, 21440009, 21447175, 21454314, 21461471, 21468617, 21475764, 21482924, 21490077, 21497235, 21504401, 21511571, 21518734, 21525890, 21533058, 21540232, 21547396, 21554556, 21561709, 21568863, 21576035, 21583203, 21590362, 21597520, 21604680, 21611852, 21619004, 21626161, 21633325, 21640491, 21647653, 21654814, 21661974, 21669146, 21676305, 21683471, 21690636, 21697804, 21704966, 21712129, 21719303, 21726465, 21733626, 21740792, 21747949, 21755110, 21762264, 21769421, 21776574, 21783739, 21790905, 21798074, 21805232, 21812397, 21819559, 21826720, 21833845, 21840991, 21848119, 21855250, 21862393, 21869537, 21876698, 21883855, 21890993, 21898155, 21905310, 21912465, 21919621, 21926782, 21933948, 21941120, 21948291, 21955462, 21962635, 21969800, 21976966, 21984128, 21991286, 21998438, 22005590, 22012750, 22019907, 22027064, 22034224, 22041393, 22048553, 22055722, 22062883, 22070044, 22077198, 22084356, 22091518, 22098694, 22105862, 22113034, 22120200, 22127350, 22134526, 22141688, 22148848, 22156001, 22163172, 22170334, 22177499, 22184669, 22191826, 22198999, 22206150, 22213305, 22220455, 22227624, 22234793, 22241970, 22249146, 22256323, 22263499, 22270667, 22277825, 22284996, 22292157, 22299326, 22306493, 22313650, 22320818, 22327989, 22335153, 22342307, 22349480, 22356658, 22363838, 22370998, 22378150, 22385293, 22392426, 22399543, 22406692, 22413825, 22420967, 22428091))
ORDER BY
    blocks.datetime ASC

2025-05-08 11:56:06,900 INFO sqlalchemy.engine.Engine [generated in 0.00021s] {}
2025-05-08 11:56:09,137 INFO sqlalchemy.engine.Engine ROLLBACK

,destination_vault_address,token_address,quantity,safe_price,backing,symbol,datetime
0,0xC064A47894349f3cc75D5edb69A2E91c0A049d4A,0xC71Ea051a5F82c67ADcF634c36FFE6334793D24C,NaN,NaN,NaN,waEthLidoGHO,2024-09-15 23:59:59+00:00
1,0x1Ea622fa030e4a78F4CC2f305dd3c08DA3F08573,0xA35b1B31Ce002FBF2058D22F30f95D405200A15b,NaN,1.038858,1.040201,ETHx,2024-09-15 23:59:59+00:00
2,0x2F7e096a400ded5D02762120b39A3aA4ABA072a4,0xA35b1B31Ce002FBF2058D22F30f95D405200A15b,2.199614e+02,1.038858,1.040201,ETHx,2024-09-15 23:59:59+00:00
3,0x60339056EC88996e41757E05a798310E46972cca,0xA35b1B31Ce002FBF2058D22F30f95D405200A15b,NaN,1.038858,1.040201,ETHx,2024-09-15 23:59:59+00:00
4,0xC001f23397dB71B17602Ce7D90a983Edc38DB0d1,0xA35b1B31Ce002FBF2058D22F30f95D405200A15b,7.042454e+02,1.038858,1.040201,ETHx,2024-09-15 23:59:59+00:00
...,...,...,...,...,...,...,...
39307,0x9906eB64BA32Fb4fD3e5541ecA95e57610084d02,0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E,4.357064e+05,0.000551,NaN,crvUSD,2025-05-06 23:59:59+00:00
39308,0xB580f62dd031c63F083CBdC4f9e5C5653036cb1B,0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E,1.844974e+06,0.000551,NaN,crvUSD,2025-05-06 23:59:59+00:00
39309,0xC099899d0278CE83976218Cbe58D01dD382dcA32,0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E,8.749651e+05,0.000551,NaN,crvUSD,2025-05-06 23:59:59+00:00
39310,0xEeEE628a00B0EDa99D1bc78a72Fa2F2Df4AdE2F4,0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E,4.357064e+05,0.000551,NaN,crvUSD,2025-05-06 23:59:59+00:00
39311,0xa345ceECCF8fe6aE33fe1D655B4806492251c2A8,0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E,1.844974e+06,0.000551,NaN,crvUSD,2025-05-06 23:59:59+00:00

In [24]:
df = pd.merge(
    token_value_df,
    destination_state_df,
    on=["datetime", "destination_vault_address"],
    how="left",
)
df["safe_value"] = df["quantity"] * df["safe_price"] * df["portion_ownership"]
df["backing_value"] = df["quantity"] * df["backing"] * df["portion_ownership"]

total_safe_and_backing_value = df.groupby(["datetime", "symbol"])[["safe_value", "backing_value"]].sum().reset_index()

safe_value_df = total_safe_and_backing_value.pivot(index="datetime", values="safe_value", columns="symbol").fillna(0)
backing_value_df = total_safe_and_backing_value.pivot(
    index="datetime", values="backing_value", columns="symbol"
).fillna(0)

px.bar(safe_value_df)

In [35]:
px.line((backing_value_df - safe_value_df))

In [64]:
df["price_return"] = 100 * (df["backing"] - df["safe_price"]) / df["backing"]

price_return_df = df.groupby(["datetime", "symbol"])["price_return"].first().reset_index()
price_return_df

                      datetime        symbol  price_return
0    2024-09-15 23:59:59+00:00          ETHx      0.129134
1    2024-09-15 23:59:59+00:00          FRAX           NaN
2    2024-09-15 23:59:59+00:00           GHO           NaN
3    2024-09-15 23:59:59+00:00          OETH      9.487218
4    2024-09-15 23:59:59+00:00          USDC           NaN
...                        ...           ...           ...
6781 2025-05-06 23:59:59+00:00  waEthLidoGHO           NaN
6782 2025-05-06 23:59:59+00:00     waEthUSDC           NaN
6783 2025-05-06 23:59:59+00:00     waEthUSDT           NaN
6784 2025-05-06 23:59:59+00:00         weETH      0.078513
6785 2025-05-06 23:59:59+00:00        wstETH      0.089353

[6786 rows x 3 columns]

In [31]:
px.line(100 * (backing_value_df.sum(axis=1) - safe_value_df.sum(axis=1)) / backing_value_df.sum(axis=1))